
name: PHP Validation

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        run: sudo apt-get update && sudo apt-get install php8.1 php8.1-dom php8.1-curl composer -y

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: ./vendor/bin/phpunit tests/


  phpstan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      run: sudo apt-get update && sudo apt-get install php8.1 php8.1-dom php8.1-curl composer -y

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install PHPStan
      run: composer require --dev phpstan/phpstan

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse